version: '3'

services:
  mysql:
    image: mysql:5.7.20
    environment:
      - "MYSQL_USER=root"
      - "MYSQL_ROOT_PASSWORD=root"
    ports:
      - 8081:8081
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:  
      - "8090:80"
    links:
      - mysql:db  

  apache:
    build: './apache_dockerfile/'
    volumes:
      - ./apache:/var/www/html
    depends_on:
      - mysql
    container_name: apache_web
    restart: always
    ports:
      - "8080:80"         
